### ISSUE TITLE
setup.bat - jemalloc is used when qt is not found

### ISSUE THREAD

**Issue by dirbasti** [xStarbound/xStarbound#1]
Hi, 

jemalloc is used based on %QT_PREFIX_PATH%. Is that intended?

I am new to programming...:
- why is jemalloc not used for Windows binaries?
- why hasn't jemalloc bumped to a recent version (for windows builds)?

**Comment by FezzedOne** [comment]
1. `jemalloc` is not needed for Windows binaries built with Visual Studio since Windows' `malloc` is good enough. (However, it's included when you're building with MinGW because MinGW's default `malloc` is not so great.)
2. Honestly, that's mostly due to me not using Visual Studio or Windows for the `.exe` builds, and thus not checking to make sure everything is up to date for Visual Studio users. I'll look into it.

**Comment by dirbasti** [comment]
...ah, got it. Thanks!
