### ISSUE TITLE
[BUG] Digital Storage broken

### ISSUE THREAD

**Issue by A-Vladimir** [xStarbound/xStarbound#21]
Brakes the digital storage interface so that no items can be put in or out.

**Comment by FezzedOne** [comment]
I need to see your `xclient.log` file. If you're running Digital Storage on a server, I also need to see your `xserver.log`.

**Comment by A-Vladimir** [comment]
[xclient.log](https://github.com/user-attachments/files/17371822/xclient.log)

**Comment by FezzedOne** [comment]
Did you uninstall any other mods recently? I'm seeing a bunch of `No such item` exceptions being thrown, crashing a script used by Digital Storage.

**Comment by A-Vladimir** [comment]
I semifixed the problem by switching from xStarbound to OpenStarbound, so I think xStarbound was blocking the script from DigitalStorage

**Comment by FezzedOne** [comment]
I'm going to test this out myself and see if I can't fix it.

**Comment by FezzedOne** [comment]
Found out what the issue is. Digital Storage's server-side code tries to smuggle tables containing functions through `world.callScriptedEntity`, which is *intentionally* not allowed on xClient when `"safeScripts"` is enabled. To be able to use Digital Storage, disable `"safeScripts"` in `xclient.config` in single-player or if you're hosting with your client, or `xserver.config` on the server. I'll add this to the mod compatibility section on the readme.

This issue has been closed.

**Comment by A-Vladimir** [comment]
then I'l rather just stick with OpenStarbound instead, disabling "safeScripts" makes some mods stop working.
