### ISSUE TITLE
[BUG] Crash to desktop when failing to connect to a server

### ISSUE THREAD

**Issue by loveaabb** [xStarbound/xStarbound#23]
## Description

The game crashes to desktop when failing to connect to a server with xclient
Possibly some unicode-related issue

Crash Log:
[xclient.log](https://github.com/user-attachments/files/17750474/xclient.log)

## Reproduction steps

1. Choose "JOIN GAME" and pick a character
2. enter some server info that do not match a running server (i use 127.0.0.1:21025 without running any server instance locally)
3. see the client crash

**Comment by FezzedOne** [comment]
Your system's language is set to Chinese, right? Well, I think this is a bug in Windows's networking stack (or whatever else) where an error string (or whatever else) isn't properly encoded UTF-8 (probably after being transformed from UTF-16 to UTF-8 via internal system code).

**Comment by FezzedOne** [comment]
Can you try building a debug build of xClient and attempting to connect to a nonexistent server again? I should be able to work around this.

**Comment by loveaabb** [comment]
> Your system's language is set to Chinese, right? 
yes

**Comment by loveaabb** [comment]
> Your system's language is set to Chinese, right?

yes

**Comment by loveaabb** [comment]
I've built a debug binary and tried the reproduction step on it
here's the log:
[xclient.log](https://github.com/user-attachments/files/17769486/xclient.log)

**Comment by FezzedOne** [comment]
That's going to be rather difficult to work around, since the iterator the text wrapping code uses needs to split the text into UTF-8 characters and know how many such characters are in the text to be wrapped. I could go ahead and set up text wrapping to be ignored if a UTF-8 error is caught, but there are so many other places in the code where UTF-8 characters need to be appropriately split or counted that I'm sure it's going to be a nightmare to «fix».

To avoid this error, I suggest not attempting to connect to servers that are down, or running xStarbound in WSL2/WSLg or on a Linux install to bypass the Windows API code that passed invalid UTF-8 text to xStarbound in the first place.

Wait, you know what? I could run a UTF-8 check on networking errors returned by the OS and discard the text if it's invalid.

**Comment by FezzedOne** [comment]
Alright, fixed the CTD. Try updating your repo and rebuilding xClient now.

**Comment by loveaabb** [comment]
thx for your work! :3
