### ISSUE TITLE
[BUG] Fishing rods not working

### ISSUE THREAD

**Issue by loveaabb** [xStarbound/xStarbound#25]
## Description

Fishing rods in xStarbound are unable to use.
I tested on OpenStarbound and original Starbound with the same saved game, their fishing rods work fine and i spotted a bit difference between how the player character hold the rod 

![fishingxsb](https://github.com/user-attachments/assets/059307f2-b2b3-4941-97cf-676ccf2347a4)
xStarbound

![fishingsb](https://github.com/user-attachments/assets/732ed647-66d7-4410-9f83-f538568d6585)
OpenStarbound & original Starbound

the wielded fishing rod in xStarbound is strangely raised at all time

## Reproduction steps

1. start a game
2. get a fishing rod
3. wield the fishing rod
4. try to use the rod

**Comment by FezzedOne** [comment]
Turns out it's a compatibility detection issue in Pluto's parser. This bug should be fixed with the commit I just pushed ([8e70acd](https://github.com/xStarbound/xStarbound/commit/8e70acdd5a39f225846de43bdf3dfbb159af4e20)).

Unfortunately, the fix does make automatic compatibility detection for the `switch` keyword overly «pessimistic», but that's better than broken Lua scripts.

**Comment by FezzedOne** [comment]
No, wait. That didn't fix it. The issue seems to be more involved.

**Comment by FezzedOne** [comment]
Alright, after a bunch of debugging and finagling, I managed to fix the issue with some more compatibility detection checks. Fixed builds will be released tonight.

**Comment by FezzedOne** [comment]
The bug has been fixed in [v3.3.1r2](https://github.com/xStarbound/xStarbound/releases/tag/v3.3.1r2) (commit [29f84d7](https://github.com/xStarbound/xStarbound/commit/29f84d7c75602ed0b06360c62178e7d973789957)).
