### ISSUE TITLE
Linux/Steam Deck: xClient gets an error when obtaining a silicon board

### ISSUE THREAD

**Issue by ERROR2401** [xStarbound/xStarbound#7]
When I was playing in singleplayer on steam deck, I found an odd bug where either obtaining or crafting a silicon board in any way will either show an error or outright crash the client depending on how it's obtained. Crafting a silicon board will result in the entire client almost immediately closing, while getting it through a loot drop or /spawnitem will quit to the title with an error stating that there was no light ocean blue repairo item for some odd reason. I installed xSB-2 through the releases files after trying to follow the instructions on the readme but failing as the scripts command couldn't recognize the make command and one other one that I can't remember. the attached log has me getting a silicon board through a drop, then shortly after closing the game manually
[xclient.log](https://github.com/FezzedOne/xSB-2/files/15382429/xclient.log)

**Comment by FezzedOne** [comment]
The code that caused the crash itself has been fixed in xSB-2 v2.5, What happened there was that xSB-2 intentionally threw an exception instead of generating a Perfectly Generic Item under that circumstance. That exception kicked you out of your game.

Keep in mind that your modpack is *really buggy* though. You should probably figure out which mod(s) is/are causing the recipe error that triggered the crash.

**Comment by FezzedOne** [comment]
The code that caused the kick itself has been fixed in xSB-2 v2.5, What happened there was that xSB-2 intentionally threw an exception instead of generating a Perfectly Generic Item under that circumstance. That exception kicked you out of your game.

Keep in mind that your modpack is *really buggy* though. You should probably figure out which mod(s) is/are causing the recipe error that triggered the crash.
